version: '2.0'

# networks
networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  # postgres
  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    image: postgres
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./data:/var/lib/postgresql/data:rw

  # guacamole
  guacamole:
    container_name: guacamole_compose
    depends_on:
     - guacd
     - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
     - guacd
    networks:
      guacnetwork_compose:
    ports:
     - 8080/tcp
    restart: always

  # nginx
  nginx:
   container_name: nginx_guacamole_compose
   restart: always
   image: nginx
   volumes:
    - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
    - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/mysite.template:/etc/nginx/conf.d/default.conf:ro
   ports:
   - 8443:443
   links:
   - guacamole
   networks:
     guacnetwork_compose:
   command: /bin/bash -c "nginx -g 'daemon off;'"

  ubuntu-desktop-lxde-vnc:
   container_name: ubuntu_descktop_lxde
   ports:
    - '6080:80'
    - '5900:5900'
   environment:
    - VNC_PASSWORD=mypassword
   volumes:
    - '/dev/shm:/dev/shm'
   image: dorowu/ubuntu-desktop-lxde-vnc

  ubuntu-desktop-lxde-vnc-focal-lxqt:
   container_name: ubuntu-desktop-lxde-vnc-focal-lxqt
   ports:
    - '6081:80'
    - '5901:5900'
   environment:
    - VNC_PASSWORD=sunway
   volumes:
    - '/dev/shm:/dev/shm'
   image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt

  ubuntu-desktop-lxde-vnc-focal:
   container_name: ubuntu-desktop-lxde-vnc-focal
   ports:
    - '6082:80'
    - '5902:5900'
   environment:
    - VNC_PASSWORD=sunway
   volumes:
    - '/dev/shm:/dev/shm'
    - /var/run/docker.sock:/tmp/docker.sock:ro
   image: dorowu/ubuntu-desktop-lxde-vnc:focal
